import { describe, expect, it, vi } from 'vitest';

import { Color } from '../../model/color/color.model';
import { Palette, PaletteEntry } from '../../model/palette/palette.model';
import type { Project } from '../../model/project/project.model';
import { downloadBlob } from '../download';
import { PdfPrinter } from './pdf.printer';

vi.mock('../download', () => ({ downloadBlob: vi.fn() }));

describe('PDF generation integration', () => {
    it('downloads a valid PDF blob generated by jsPDF with the embedded font', async () => {
        const entry = new PaletteEntry('Red', new Color(255, 0, 0, 255));
        entry.ref = 'P01';
        entry.symbol = 'A';
        entry.prefix = 'P';
        const project = {
            boardConfiguration: {
                board: { nbBeadPerRow: 1 },
                nbBoardWidth: 1,
                nbBoardHeight: 1,
            },
            paletteConfiguration: { palettes: [new Palette('Test', [entry])] },
            exportConfiguration: { useSymbols: true },
        } as Project;

        await new PdfPrinter().print(
            new Uint8ClampedArray([255, 0, 0, 255]),
            new Map([['P01', 1]]),
            project,
            'pattern'
        );

        expect(downloadBlob).toHaveBeenCalledOnce();
        const [blob, filename] = vi.mocked(downloadBlob).mock.calls[0];
        expect(filename).toBe('pattern.pdf');
        expect(blob).toBeInstanceOf(Blob);
        expect(blob.type).toBe('application/pdf');
        const contents = await blob.text();
        expect(contents).toMatch(/^%PDF-/);
        expect(contents).toContain('/Count 3');
        expect(contents).toContain('/FontFile2');
        expect(contents).toMatch(/%%EOF$/);
    });
});
