import { photoGuideCopy } from './photo';
import type { GuideTranslations } from './types';

export const frenchGuides: GuideTranslations = {
    'photo-to-perler-bead-pattern': photoGuideCopy.fr,
    'perler-bead-pegboards': {
        title: 'Choisir la taille des plaques pour perles à repasser',
        description: 'Comprenez les dimensions des grilles, le nombre de plaques et l’échelle d’impression. Téléchargez une grille vide 29 × 29 avec repères de contrôle.',
        eyebrow: 'Plaques à picots',
        intro: 'La plaque détermine les dimensions de la grille et le niveau de détail possible. La marque de perles détermine les couleurs disponibles. Ces deux choix sont indépendants.',
        sections: [
            { heading: 'Choisir séparément la marque et la plaque', body: ['Les perles et la plaque peuvent venir de fabricants différents, à condition que leurs dimensions réelles soient compatibles. Une palette Perler peut servir avec une grille Midi adaptée, mais vérifiez que vos perles s’insèrent sur votre plaque.', 'Dans le générateur, la marque sert à associer les couleurs. La plaque définit les dimensions du modèle.'] },
            { heading: 'Assembler plusieurs plaques pour un grand modèle', body: ['Le nombre de plaques en largeur et en hauteur multiplie la taille choisie. Une plaque de 29 × 29 donne une grille de 29 × 29 ; deux plaques côte à côte donnent 58 × 29.', 'Un grand modèle peut conserver davantage de détails. Il demande aussi plus de perles, plus de temps de repassage et un assemblage plus soigneux.'] },
            { heading: 'Vérifier le nombre de perles avant l’export', body: ['Une grande grille peut vite représenter plusieurs milliers de perles. Vérifiez le nombre total et la liste des couleurs avant de vous lancer.'], bullets: ['Pour une petite icône, une plaque suffit généralement.', 'Pour un portrait de personnage, commencez avec deux plaques ou plus.', 'Pour une photo détaillée, comparez plusieurs tailles avant d’exporter.'] },
            { heading: 'Imprimer un PDF de la bibliothèque à la bonne échelle', body: ['Les PDF prêts à télécharger dans la bibliothèque comportent un repère de 50 mm. Dans la fenêtre d’impression, choisissez 100 % ou « Taille réelle » et désactivez l’ajustement à la page. Imprimez d’abord une seule page.', 'Mesurez le repère avec une règle : il doit faire 50 mm. Sinon, corrigez l’échelle d’impression et recommencez. Comparez aussi la grille avec votre vraie plaque avant de l’utiliser comme gabarit dessous.', 'Ce contrôle concerne les PDF de la bibliothèque munis du repère. Un export de l’éditeur peut avoir une autre mise en page : suivez-le en comptant les cases tant que son espacement n’a pas été vérifié. Changer de palette ne transforme pas une grille Midi en gabarit Mini ou Maxi à taille réelle.'] },
            { heading: 'Télécharger une grille vide pour contrôler l’imprimante', body: ['Choisissez A4 ou US Letter selon votre papier. Chaque feuille gratuite contient une grille vide de 29 × 29 avec un pas de 5 mm et deux repères de 50 mm, horizontal et vertical. La grille mesure 145 mm sur son bord extérieur ; les centres de la première et de la dernière case sont séparés de 140 mm.', 'Imprimez à 100 % ou en taille réelle, sans ajustement à la page. Mesurez les deux repères. Si l’un ne fait pas 50 mm, corrigez la mise à l’échelle et réimprimez. Vérifiez séparément votre plaque : ces fichiers ont été contrôlés numériquement, sans essai sur une plaque physique.', 'Utilisez la grille pour dessiner un motif ou préparer une activité de groupe. Les SVG modifiables ont les mêmes dimensions, mais un logiciel de dessin peut les redimensionner à l’import. Mesurez une nouvelle impression après modification. Ces feuilles ne changent pas l’échelle d’un ancien export de l’éditeur.'] },
        ],
    },
    'perler-to-hama-artkal': {
        title: 'Convertir un modèle Perler aux couleurs Hama ou Artkal',
        description: 'Changez la marque de perles dans l’éditeur en conservant la disposition du motif, puis exportez une nouvelle grille et sa liste de couleurs.',
        eyebrow: 'Couleurs des perles',
        intro: 'Un modèle prêt à l’emploi peut être utilisé avec une autre palette. Les aperçus et téléchargements standard de la bibliothèque utilisent Perler Midi. Ouvrez le motif dans l’éditeur, changez uniquement la marque de perles et exportez la grille adaptée.',
        sections: [
            { heading: '1. Ouvrir un modèle existant', body: ['Depuis la page du motif, ouvrez l’éditeur puis confirmez l’ouverture du modèle. Si un autre projet est déjà ouvert, enregistrez-le avant de remplacer le motif en cours.', 'Prenons la poule bleue de Stardew Valley. La version Perler originale utilise 192 perles en 8 couleurs, avec un motif de 16 × 16 sur une plaque de 29 × 29. L’éditeur charge directement la grille de perles : inutile d’importer ou de recopier l’aperçu.'] },
            { heading: '2. Changer de marque et appliquer', body: ['Dans « Réglages du modèle », à côté de la grille ou dans le panneau de réglages sur téléphone, choisissez Hama Midi ou votre série Artkal sous « Marque de perles ». Gardez la plaque et le nombre de plaques inchangés, puis choisissez « Appliquer ».', 'Un changement de marque seul conserve les positions, les cases vides et les retouches. Les couleurs reconnues comme noir ou blanc dans la palette actuelle gardent ce nom si un équivalent est activé dans la nouvelle palette. Les autres sont associées à la couleur numérique activée la plus proche. Modifier les dimensions de la plaque est une opération distincte qui peut reconstruire la grille.', 'Enregistrez une copie du projet avant de changer de marque. Les retouches sont conservées, mais l’historique d’annulation repart de zéro après le changement de palette. Rouvrez la copie pour retrouver exactement les anciennes couleurs.'], figure: {
                alt: 'Poule bleue dans l’éditeur en anglais, avec Hama Midi, 192 perles et la même plaque de 29 × 29.',
                caption: 'Résultat du passage à Hama Midi dans l’éditeur. L’interface de cette capture est en anglais ; les couleurs numériques ne constituent pas une vérification des perles physiques.',
            } },
            { heading: '3. Examiner les nouvelles couleurs', body: ['Contrôlez les contours, le visage et les petits détails. Plusieurs couleurs Perler proches peuvent devenir une même couleur Hama ou Artkal. Le nombre de couleurs peut donc diminuer sans changer la disposition. Retouchez quelques perles si un détail manque de contraste.', 'La correspondance utilise des valeurs numériques, pas des mesures de vos perles. Comparez les noms et codes avec votre stock. Elle ne vérifie ni la taille des perles, ni leur adaptation à la plaque, ni leur compatibilité au repassage.'] },
            { heading: '4. Exporter le modèle converti', body: ['Ouvrez l’export au-dessus de la grille, ou depuis le menu des fichiers sur téléphone. Choisissez PDF dans « Format d’export », indiquez la marque dans le nom du fichier et exportez le PDF. Activez « Utiliser des symboles dans les exports imprimables » pour distinguer les couleurs par des symboles.', 'Utilisez cette nouvelle grille et sa liste de couleurs pour prévoir les quantités. Le PDF et le PNG de la page d’origine restent la version Perler : vos modifications ne remplacent pas les téléchargements de la bibliothèque.', 'Enregistrez également un projet modifiable avec la nouvelle palette. Avant de poser les perles, comparez l’impression à l’écran et vérifiez les couleurs nécessaires.'] },
        ],
    },
    'perler-vs-hama-vs-artkal': {
        title: 'Perler, Hama ou Artkal : tailles, couleurs et mélanges',
        description: 'Comparez les gammes Mini et Midi de Perler, Hama et Artkal, les dimensions, les couleurs et les indications des fabricants sur les mélanges.',
        eyebrow: 'Choisir ses perles',
        intro: 'Commencez par les dimensions de vos perles et de votre plaque, puis vérifiez les couleurs du motif. La série inscrite sur le sachet compte autant que la marque. Ce guide compare les informations des fabricants ; il ne repose pas sur un essai de fusion réalisé par notre équipe.',
        sections: [
            { heading: 'Les dimensions en un coup d’œil', body: ['Les perles standard ou Midi et les Mini nécessitent des espacements différents. Même deux gammes appelées Mini peuvent avoir des dimensions différentes. Vérifiez la série exacte et les perles recommandées pour votre plaque avant de commander.'], table: {
                caption: 'Dimensions annoncées par les fabricants pour les séries comparées', headers: ['Gamme', 'Dimensions', 'Plaque à choisir'], rows: [
                    { label: 'Perler standard', cells: ['5,07 mm de haut × 4,77 mm de large', 'Utiliser une plaque prévue pour les perles Perler standard.'] },
                    { label: 'Hama Midi', cells: ['5 mm de diamètre × 5 mm de haut', 'Choisir une plaque Hama Midi ou vérifier l’ajustement exact.'] },
                    { label: 'Artkal S', cells: ['5 mm Midi ; série rigide', 'Choisir une plaque pour la gamme 5 mm. S n’est pas une gamme Mini.'] },
                    { label: 'Perler Mini', cells: ['Gamme Mini distincte', 'Perler réserve ses plaques Mini aux perles Mini, et non aux standard.'] },
                    { label: 'Hama Mini', cells: ['2,5 mm de diamètre × 2,5 mm de haut', 'Choisir une plaque pour Hama Mini.'] },
                    { label: 'Artkal C', cells: ['2,6 mm Mini ; série rigide', 'Choisir une plaque pour la gamme Artkal Mini de 2,6 mm.'] },
                ],
            } },
            { heading: 'Quelle gamme choisir ?', body: ['Un kit avec perles et plaque assorties est un point de départ simple. Si vous avez déjà du matériel, conserver la même série permet de réutiliser vos plaques et couleurs triées. Vérifiez que les couleurs les plus utilisées peuvent être rachetées.', 'Pour un petit ouvrage détaillé, envisagez une gamme Mini avec sa plaque. Une grille de 29 × 29 conserve 29 positions de chaque côté, quelle que soit la taille des perles. Les Mini réduisent la taille physique ; davantage de détails exige davantage de cases.'], bullets: ['Vous possédez des Perler standard ? Vérifiez les couleurs manquantes avant de remplacer votre matériel.', 'Vous avez du Hama ? Identifiez Mini, Midi ou Maxi avant de compléter votre stock ou de choisir une palette.', 'Chez Artkal, S correspond aux Midi rigides de 5 mm et C aux Mini rigides de 2,6 mm. Les séries souples R et A sont des produits distincts.'] },
            { heading: 'Peut-on mélanger Perler, Hama et Artkal ?', body: ['Vérifiez les dimensions et les séries exactes. Dans une déclaration du 24 mars 2017, Artkal présente ses séries rigides améliorées S de 5 mm et C de 2,6 mm comme compatibles avec Perler et Hama. La marque recommande d’utiliser séparément ses séries souples R de 5 mm et A de 2,6 mm pour conserver leur souplesse.', 'Cette déclaration vise des séries précises et ne garantit pas tous les mélanges ni toutes les plaques. Hama annonce 2,5 mm pour Mini, contre 2,6 mm pour Artkal C. Le nom Mini ne suffit pas à confirmer une même plaque ou un même comportement à la chaleur.', 'Gardez les mélanges non identifiés à part. Pour une combinaison dont vous avez vérifié l’ajustement sur la plaque, suivez les instructions des fabricants et commencez par un petit essai. Examinez-le après refroidissement avant de repasser un grand motif.'] },
            { heading: 'Comparer les couleurs utiles, puis le coût', body: ['Préparez une liste à partir du motif : série, code couleur et finition, surtout pour les contours, carnations et nuances proches. Deux couleurs nommées rouge ne sont pas nécessairement identiques en réalité.', 'Consultez les nuanciers puis la disponibilité des quantités nécessaires. Hama propose des cartes par taille, Artkal par série ; les sachets Perler permettent de vérifier les couleurs individuelles. Le nombre total de couleurs d’une marque ne garantit pas la nuance voulue pour votre projet.', 'Comparez le coût livré de votre liste, en incluant les frais de port et une éventuelle nouvelle plaque. Un grand seau mélangé peut manquer de la couleur dominante. Un sachet uni plus cher peut alors être plus utile. Les prix et les stocks locaux évoluent.'] },
            { heading: 'Utiliser une grille Perler avec les couleurs Hama ou Artkal', body: ['Les téléchargements standard de notre bibliothèque utilisent Perler Midi. Pour une autre gamme, ouvrez le motif dans l’éditeur et sélectionnez-la sous « Marque de perles ». Artkal S (5 mm) désigne la palette S et Artkal C la palette C. Conservez les réglages de plaque pour ne changer que les couleurs.', '« Appliquer » conserve la disposition et associe les couleurs aux teintes numériques activées. Contrôlez les détails et exportez une nouvelle liste. Cela aide à prévoir les fournitures, sans certifier les couleurs physiques, l’ajustement sur la plaque ou la compatibilité de fusion.', 'Le PDF d’origine reste la version Perler. Une grille à compter peut être suivie case par case avec une autre taille de perles. Un gabarit sous une plaque transparente exige un espacement physique vérifié ; le choix de palette ne définit pas cet espacement.'] },
            { heading: 'Tester le matériel avant le grand motif', body: ['Suivez les consignes de votre série. Perler conseille un fer sans vapeur à chaleur moyenne et un petit essai. Hama donne des réglages différents pour Mini, Midi et Maxi et recommande aussi de tester, car les fers varient. Une durée ou un réglage n’est pas universel pour les trois marques.', 'Confiez le repassage à un adulte, utilisez le papier recommandé et gardez le fer en mouvement. Laissez refroidir l’essai avant de vérifier les jonctions. Une fois les perles, la plaque et les couleurs choisies, commencez par un petit modèle.'] },
        ],
    },
    'mini-perler-beads': {
        title: 'Les perles Mini pour des motifs petits et détaillés',
        description: 'Choisissez une palette et une plaque adaptées aux perles Mini. Téléchargez de petits modèles et suivez leur grille en comptant les cases.',
        eyebrow: 'Perles Mini',
        intro: 'Les Mini permettent de réunir de nombreuses cases dans un ouvrage physiquement plus petit. Elles changent l’échelle de l’objet fini, pas la méthode de conversion de l’image.',
        sections: [
            { heading: 'Six petits modèles à télécharger', body: ['Chacun de ces motifs tient dans 16 × 16 positions au maximum. Choisissez une image pour accéder au PDF gratuit, à la liste de couleurs et à l’éditeur.', 'Ces petits dessins utilisent par défaut Perler Midi. Mini désigne la taille des perles, pas le nombre de cases. Suivez les étapes suivantes pour les réaliser avec des Mini.'] },
            { heading: 'Suivre une petite grille avec des Mini', body: ['Utilisez une plaque Mini adaptée à vos perles. Suivez les lignes et colonnes : une case remplie correspond à une perle, une case vide reste vide. Il n’est pas nécessaire d’agrandir le motif pour remplir la plaque.', 'Les PDF de la bibliothèque sont préparés pour une grille Midi. Utilisez-les comme tableaux à compter, pas comme gabarits à taille réelle sous une plaque Mini. Changer de palette ne modifie pas l’espacement imprimé.'] },
            { heading: 'Adapter les couleurs à votre gamme Mini', body: ['Ouvrez le modèle dans l’éditeur et confirmez son import. Si vous avez déjà un projet ouvert, enregistrez-le avant de remplacer le motif.', 'Dans « Réglages du modèle », choisissez votre gamme sous « Marque de perles » : Perler Mini, Hama Mini ou Artkal C, par exemple. Artkal C est une gamme Mini de 2,6 mm ; Artkal S est une gamme Midi de 5 mm. Conservez la plaque et son nombre en largeur et en hauteur, puis choisissez « Appliquer ». La grille numérique reste en place, mais la compatibilité de votre plaque physique n’est pas vérifiée.', 'Examinez les couleurs et détails avant d’exporter un nouveau PDF. Plusieurs couleurs originales peuvent devenir une seule teinte Mini. Comparez les codes et noms avec vos perles et comptez les cases tant que l’espacement réel de l’impression n’a pas été vérifié.', 'Changer la plaque est une opération distincte qui peut reconstruire la grille. Pour créer un nouveau motif utilisant toute la grille d’une plaque Mini, sélectionnez le préréglage Mini correspondant.'] },
            { heading: 'La taille des perles ne change pas l’algorithme', body: ['Une grille de 50 × 50 contient 2 500 positions, avec des Midi comme avec des Mini. La différence porte sur les dimensions de l’objet, pas sur la logique du modèle.', 'Pour générer la grille, concentrez-vous sur la palette et le nombre de cases. Pour la réalisation, faites correspondre les perles à votre vraie plaque.'] },
            { heading: 'Réaliser de petits ouvrages détaillés', body: ['Les Mini conviennent aux porte-clés, boucles d’oreilles, décorations et sprites détaillés qui seraient trop grands en Midi.', 'Elles sont plus difficiles à poser à la main. Une pince et une grille bien lisible facilitent les petits détails.'] },
            { heading: 'Choisir soigneusement la palette', body: ['Certaines gammes Mini offrent moins de couleurs que les Midi. Si des nuances importantes disparaissent, essayez une autre palette ou simplifiez l’image de départ.'] },
        ],
    },
    'perler-bead-kits-and-storage': {
        title: 'Débuter les perles à repasser : matériel et rangement',
        description: 'Préparez un kit simple avec perles, plaque, papier de repassage et pince. Triez les couleurs selon les noms et codes de vos modèles.',
        eyebrow: 'Matériel de départ',
        intro: 'Un bon équipement de départ permet d’essayer des motifs sans perdre du temps à chercher les couleurs. Commencez simplement, puis ajoutez du rangement et des plaques spéciales selon vos projets.',
        sections: [
            { heading: 'Que doit contenir un kit pour débuter ?', body: ['Prévoyez un assortiment de perles, au moins une plaque carrée, du papier de repassage et assez de couleurs courantes pour de petits projets.', 'La pince est facultative pour les motifs très simples, mais devient utile pour les petits détails et les perles Mini.'], bullets: ['Un assortiment de perles ou une petite palette.', 'Une plaque carrée ou des plaques emboîtables.', 'Du papier de repassage ou du papier cuisson adapté.', 'Une pince pour placer les perles avec précision.'] },
            { heading: 'Ranger les couleurs pour gagner du temps', body: ['Suivre une grille est plus rapide avec des perles triées par couleur. Petits tiroirs, boîtes fermées ou plateaux à compartiments sont plus pratiques qu’un mélange unique.', 'Pour les modèles riches en couleurs, étiquetez les compartiments avec les noms ou codes utilisés dans l’export du générateur.'] },
            { heading: 'Générer quelques modèles avant d’acheter en quantité', body: ['Convertissez plusieurs motifs et observez les couleurs les plus utilisées. Vous pourrez acheter les quantités réellement utiles plutôt que choisir au hasard.'] },
        ],
    },
    'how-to-iron-perler-beads': {
        title: 'Comment repasser les perles Perler',
        description: 'Suivez la méthode standard de Perler, contrôlez les jonctions et corrigez les bords mal soudés, le papier collant ou une chaleur excessive.',
        eyebrow: 'Terminer le motif',
        intro: 'Un adulte doit repasser le motif avec du papier de repassage et un fer sans vapeur réglé sur chaleur moyenne. Gardez le fer en mouvement, laissez refroidir la première face, retirez le motif de la plaque puis repassez le verso. Les perles doivent tenir ensemble tout en conservant leurs trous.',
        sections: [
            { heading: 'Avant de commencer', body: ['Ces étapes suivent la méthode standard de Perler. Consultez les instructions de vos perles, surtout pour Mini, Biggie ou une autre marque.', 'Gardez la grille à portée de main pour vérifier une dernière fois les positions et couleurs manquantes. L’aperçu numérique montre la disposition, mais ne prouve pas que les perles physiques sont soudées.'], bullets: ['Le motif posé sur sa plaque adaptée.', 'Un fer domestique, du papier de repassage et une surface plane résistante à la chaleur.', 'Quelques perles supplémentaires pour un petit essai.'] },
            { heading: '1. Tester le fer et couvrir les perles', body: ['Désactivez la vapeur. Commencez à chaleur moyenne et testez quelques perles avant le motif terminé. Les fers varient : un réglage ne garantit pas une température précise.', 'Aplatissez les plis du papier et couvrez le motif. Le fer ne doit toucher ni les perles découvertes ni la plaque.'] },
            { heading: '2. Souder régulièrement la première face', body: ['Déplacez le fer en petits cercles sur le papier, sans appuyer. Passez sur l’ensemble du motif, y compris les bords. Observez les contours voisins se rejoindre tout en gardant les trous ouverts.', 'Perler indique environ 10–20 secondes par face comme point de départ. Les couleurs et les dimensions influencent la durée : vérifiez les jonctions plutôt que de vous fier uniquement au chronomètre.'] },
            { heading: '3. Laisser refroidir, retourner et repasser le verso', body: ['Laissez refroidir la première face avant d’enlever le papier et de retirer le motif de la plaque. Retournez-le, couvrez la face non soudée et répétez le repassage. Laissez refroidir complètement avant de manipuler.', 'Comparez le résultat à la grille. Si les trous servent à assembler le projet, vérifiez-les aussi : une fusion excessive peut les fermer.'] },
            { heading: 'Si les perles se séparent ou collent au papier', body: ['Bords mal soudés : recherchez les zones insuffisamment chauffées. Perler conseille d’augmenter légèrement la température si elles ne se rejoignent pas. Procédez progressivement, sans passer directement au maximum.', 'Papier collant : attendez un peu plus longtemps puis décollez lentement. Si des perles se soulèvent avec le papier, replacez-les et repassez les zones concernées.', 'Trous fermés ou plaque déformée : la chaleur peut être excessive. Réduisez-la et contrôlez votre essai avant de continuer. Appuyer plus fort ne résout pas le problème.'] },
            { heading: 'Faut-il utiliser la méthode au ruban adhésif ?', body: ['C’est une alternative pour les grands projets, pas une étape supplémentaire de la méthode standard. Perler la présente comme un moyen de réduire les raccords entre plaques et les perles qui sautent pendant le repassage. Elle nécessite une préparation distincte et un transfert soigneux avant de chauffer.', 'Suivez l’intégralité des instructions illustrées du fabricant pour un grand projet. Perler précise que sa méthode au ruban adhésif ne convient pas aux Mini Beads.'] },
            { heading: 'Choisir un petit motif pour la suite', body: ['Notre sélection de modèles faciles contient des formes reliées tenant sur une plaque de 29 × 29 avec peu de couleurs. Téléchargez la grille, vérifiez votre stock, puis posez les perles avant d’utiliser ce guide de finition.', 'Les grilles standard utilisent Perler Midi. Les convertir aux couleurs Hama ou Artkal dans l’éditeur ne confirme pas que les marques physiques peuvent être mélangées ou repassées au même réglage.'] },
        ],
    },
};
